=== pyloid/pyloid/src/pyloid/builder/build_config.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "required": ["before_build", "name", "main_script", "datas", "excludes", "icon", "bundle"],
    "properties": {
      "before_build": {
        "type": "object",
        "properties": {
          "cleanup_patterns": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "List of file patterns to clean up in the library folder before building (used to remove files that cannot be excluded through pyinstaller) - default path is site-packages"
          }
        }
      },
      "name": {
        "type": "string",
        "description": "Application name"
      },
      "main_script": {
        "type": "string",
        "description": "Path to the main Python script"
      },
      "datas": {
        "type": "array",
        "items": {
          "type": "array",
          "minItems": 2,
          "maxItems": 2,
          "items": [
            { "type": "string" },
            { "type": "string" }
          ]
        },
        "description": "List of data files to include [source path, destination path]"
      },
      "excludes": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "description": "List of modules to exclude during build with pyinstaller"
      },
      "icon": {
        "type": "string",
        "description": "Path to the application icon file"
      },
      "bundle": {
        "type": "object",
        "properties": {
          "windows": {
            "type": "string",
            "enum": ["onefile", "directory"],
            "description": "Windows build type"
          },
          "macos": {
            "type": "string",
            "enum": ["app"],
            "description": "macOS build type"
          },
          "linux": {
            "type": "string",
            "enum": ["onefile", "directory"],
            "description": "Linux build type"
          }
        },
        "required": ["windows", "macos", "linux"],
        "description": "Build settings for each OS"
      }
    }
  }

=== pyloid/pyloid/build_config.json
{
  "$schema": "./src/pyloid/builder/build_config.schema.json",
  "before_build": {
    "cleanup_patterns": [
      "PySide6/opengl32sw.dll",
      "PySide6/translations"
    ]
  },
  "name": "pyloid-app",
  "main_script": "main.py",
  "datas": [
    ["src-pyloid/icons/", "src-pyloid/icons/"],
    ["dist-front/", "dist-front/"]
  ],
  "excludes": [
    "PySide6.QtQml",
    "PySide6.QtTest",
    "PySide6.Qt3D",
    "PySide6.QtSensors",
    "PySide6.QtCharts",
    "PySide6.QtGraphs",
    "PySide6.QtDataVisualization",
    "PySide6.QtQuick",
    "PySide6.QtDesigner",
    "PySide6.QtUiTools",
    "PySide6.QtHelp"
  ],
  "icon": "src-pyloid/icons/icon.ico",
  "bundle": {
    "windows": "onefile",
    "macos": "app",
    "linux": "directory"
  }
}
